/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIterface;

import Business.AirPlaneFleet;
import Business.AirPlanes;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Abhilash
 */
public class CreateJPanel extends javax.swing.JPanel {

    private AirPlaneFleet apf;

    public CreateJPanel(AirPlaneFleet apf) {
        this.apf = apf;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        planeTypeTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        modelNoTextField = new javax.swing.JTextField();
        availSeatsTextField = new javax.swing.JTextField();
        manuTextField = new javax.swing.JTextField();
        destinationTextField = new javax.swing.JTextField();
        startTextField = new javax.swing.JTextField();
        departTextField = new javax.swing.JTextField();
        airlinerTextField = new javax.swing.JTextField();
        serialTextField = new javax.swing.JTextField();
        createBtn = new javax.swing.JButton();
        yesCheckBox = new javax.swing.JCheckBox();
        noCheckBox = new javax.swing.JCheckBox();
        licenseCheckBox = new javax.swing.JCheckBox();
        licenseExpiredCheckBox = new javax.swing.JCheckBox();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("                            AirPlane Details");

        jLabel2.setText("Availability");

        jLabel3.setText("Model Number ");

        jLabel4.setText("Departure Time");

        jLabel5.setText("Start Point");

        jLabel6.setText("Manufactured Year");

        jLabel7.setText("Destination");

        jLabel8.setText("Available Seats");

        jLabel9.setText("Airliner");

        jLabel10.setText("AirPlane Type");

        jLabel11.setText("License ");

        jLabel12.setText("Serial Number");

        availSeatsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availSeatsTextFieldActionPerformed(evt);
            }
        });
        availSeatsTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                availSeatsTextFieldKeyPressed(evt);
            }
        });

        manuTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                manuTextFieldKeyPressed(evt);
            }
        });

        departTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departTextFieldActionPerformed(evt);
            }
        });

        serialTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                serialTextFieldKeyPressed(evt);
            }
        });

        createBtn.setText("Save");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        yesCheckBox.setText("Yes");

        noCheckBox.setText("No");

        licenseCheckBox.setText("Valid");
        licenseCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licenseCheckBoxActionPerformed(evt);
            }
        });

        licenseExpiredCheckBox.setText("Expired");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(modelNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(317, 317, 317)
                            .addComponent(planeTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(514, 514, 514)
                        .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(158, 158, 158))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(yesCheckBox)
                            .addGap(33, 33, 33)
                            .addComponent(noCheckBox))
                        .addComponent(departTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(manuTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(availSeatsTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(airlinerTextField)
                            .addComponent(serialTextField)
                            .addComponent(destinationTextField))
                        .addGap(72, 72, 72))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(licenseCheckBox)
                        .addGap(58, 58, 58)
                        .addComponent(licenseExpiredCheckBox)
                        .addContainerGap(85, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(997, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(yesCheckBox)
                                            .addComponent(noCheckBox))
                                        .addGap(38, 38, 38))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(destinationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(24, 24, 24)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(departTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(startTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(manuTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)
                                .addComponent(airlinerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(availSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(serialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(planeTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(modelNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addComponent(createBtn)
                        .addGap(93, 93, 93))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(licenseCheckBox)
                            .addComponent(licenseExpiredCheckBox)
                            .addComponent(jLabel11))
                        .addGap(216, 216, 216))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(174, 174, 174)
                    .addComponent(jLabel4)
                    .addContainerGap(417, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void departTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departTextFieldActionPerformed

    private void availSeatsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availSeatsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availSeatsTextFieldActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:

        String dtime = departTextField.getText().trim();
        String manyear = manuTextField.getText();
        String seatss = availSeatsTextField.getText();
        int manuYear = Integer.parseInt((manuTextField.getText().trim()));
        int seats = Integer.parseInt(availSeatsTextField.getText().trim());
        String planetype = planeTypeTextField.getText().trim();
        String Model = modelNoTextField.getText().trim();
        String destination = destinationTextField.getText().trim();
        String startpoint = startTextField.getText().trim();
        String airliner = airlinerTextField.getText().trim();
        String serial = serialTextField.getText().trim();

        if (seatss.equals("") || manyear.equals("") || planetype.equals("") || Model.equals("") || destination.equals("") || startpoint.equals("") || airliner.equals("") || serial.equals("")) {
            JOptionPane.showMessageDialog(null, " Few Fields are left empty");
        } else {

            AirPlanes a = apf.addPlanes();

            if (licenseCheckBox.isSelected()) {
                String license = "valid";
                a.setLicense(license);
            }
            if (licenseExpiredCheckBox.isSelected()) {
                String license = "Expired";
                a.setLicense(license);
            }

            if (yesCheckBox.isSelected()) {
                String availability = "Yes";
                a.setAvailablity(availability);
            } else {
                a.setAvailablity("No");
            }
            if (noCheckBox.isSelected()) {
                String availability = "No";
                a.setAvailablity(availability);
            }
            a.setDeparture(dtime);
            a.setManufacturedyear(manuYear);
            a.setAvailableSeats(seats);
            a.setType(planetype);
            a.setModelNumber(Model);
            a.setDestination(destination);
            a.setStartPoint(startpoint);
            a.setAirliner(airliner);
            a.setSerialNumber(serial);

            JOptionPane.showMessageDialog(null, "The details for new plane has been entered");

            yesCheckBox.setSelected(false);
            departTextField.setText("");
            manuTextField.setText("");
            availSeatsTextField.setText("");
            planeTypeTextField.setText("");
            modelNoTextField.setText("");
            destinationTextField.setText("");
            startTextField.setText("");
            airlinerTextField.setText("");
            //licenseTextField.setText(""); 
            licenseCheckBox.setSelected(false);
            serialTextField.setText("");

        }
    }//GEN-LAST:event_createBtnActionPerformed

    private void licenseCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenseCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_licenseCheckBoxActionPerformed

    private void availSeatsTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_availSeatsTextFieldKeyPressed
        // TODO add your handling code here:
        if (availSeatsTextField.getText().length() <= 2) {
            evt.consume();
        } else {
            availSeatsTextField.setEditable(false);
            JOptionPane.showMessageDialog(null, "Maximum allowed seats are 300");
            availSeatsTextField.setText("");
        }
        int key = evt.getKeyCode();
        if ((key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9) || (key >= KeyEvent.VK_0 && key <= evt.VK_9) || (key == evt.VK_BACK_SPACE)) {
            availSeatsTextField.setEditable(true);
        } else {
            availSeatsTextField.setEditable(false);
            JOptionPane.showMessageDialog(null, " Input format should be in numbers");
            availSeatsTextField.setText("");

        }
    }//GEN-LAST:event_availSeatsTextFieldKeyPressed

    private void serialTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serialTextFieldKeyPressed
        // TODO add your handling code here:

        int key = evt.getKeyCode();
        if ((key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9) || (key >= evt.VK_0 && key <= evt.VK_9) || (key == evt.VK_BACK_SPACE)) {
            serialTextField.setEditable(true);
        } else {
            serialTextField.setEditable(false);
            JOptionPane.showMessageDialog(null, " Input should be in a number format");
            serialTextField.setText("");

        }
    }//GEN-LAST:event_serialTextFieldKeyPressed

    private void manuTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_manuTextFieldKeyPressed
        // TODO add your handling code here:

        if (manuTextField.getText().length() <= 3) {
            evt.consume();
        } else {
            manuTextField.setEditable(false);
            JOptionPane.showMessageDialog(null, " Input format must be YYYY ");
            manuTextField.setText("");
        }
        int key = evt.getKeyCode();
        if ((key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9) || (key >= evt.VK_0 && key <= evt.VK_9) || (key == evt.VK_BACK_SPACE)) {
            manuTextField.setEditable(true);
        } else {
            manuTextField.setEditable(false);
            JOptionPane.showMessageDialog(null, " Input format must be numbers");
            manuTextField.setText("");

        }
    }//GEN-LAST:event_manuTextFieldKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField airlinerTextField;
    private javax.swing.JTextField availSeatsTextField;
    private javax.swing.JButton createBtn;
    private javax.swing.JTextField departTextField;
    private javax.swing.JTextField destinationTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JCheckBox licenseCheckBox;
    private javax.swing.JCheckBox licenseExpiredCheckBox;
    private javax.swing.JTextField manuTextField;
    private javax.swing.JTextField modelNoTextField;
    private javax.swing.JCheckBox noCheckBox;
    private javax.swing.JTextField planeTypeTextField;
    private javax.swing.JTextField serialTextField;
    private javax.swing.JTextField startTextField;
    private javax.swing.JCheckBox yesCheckBox;
    // End of variables declaration//GEN-END:variables
}
