/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CompanyMemberOrganization.CompanyMember;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.IndividualWorkRequest;
import Business.WorkQueue.WorkRequest;

import Business.Organization.CompanyMemberOrganization;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JAI
 */
public class CompanyMemberEarnASmileJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EarnASmileJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount account;
    private Enterprise enterprise;
    private CompanyMemberOrganization companyMemberOrganization;
    private WorkRequest workrequest;



    public CompanyMemberEarnASmileJPanel(JPanel userProcessContainer, CompanyMemberOrganization companyMemberOrganization, UserAccount account, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.account = account;
        this.enterprise = enterprise;
        this.companyMemberOrganization = companyMemberOrganization;
        workrequest = new WorkRequest();
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequestWorkqueue = new javax.swing.JTable();
        btnRequestorProfile = new javax.swing.JButton();
        completeDescriptionBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        completeDescTextArea = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        earnSmileBtn = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        jLabel1.setText("Earn A Smile");

        jLabel6.setText("Select Individual/Team help:");

        tblRequestWorkqueue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Description", "Requestor", "Selector"
            }
        ));
        tblRequestWorkqueue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRequestWorkqueueMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblRequestWorkqueueMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblRequestWorkqueue);
        if (tblRequestWorkqueue.getColumnModel().getColumnCount() > 0) {
            tblRequestWorkqueue.getColumnModel().getColumn(2).setResizable(false);
        }

        btnRequestorProfile.setText("See Requestor's Profile");
        btnRequestorProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestorProfileActionPerformed(evt);
            }
        });

        completeDescriptionBtn.setText("See Complete Description");
        completeDescriptionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeDescriptionBtnActionPerformed(evt);
            }
        });

        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        completeDescTextArea.setColumns(20);
        completeDescTextArea.setRows(5);
        jScrollPane2.setViewportView(completeDescTextArea);

        jLabel8.setText("Complete WorkDescription : ");

        earnSmileBtn.setText("Earn Smile");
        earnSmileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                earnSmileBtnActionPerformed(evt);
            }
        });

        jRadioButton1.setText("Individual");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Team");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addComponent(btnRequestorProfile)
                .addGap(52, 52, 52)
                .addComponent(earnSmileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(completeDescriptionBtn))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(backBtn))
                        .addGap(395, 810, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(completeDescriptionBtn)
                        .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(168, 168, 168)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))
                        .addGap(59, 59, 59)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRequestorProfile)
                    .addComponent(earnSmileBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents



   
    
    
    
    
   public void populateTable(CompanyMemberOrganization companyMemberOrganization) {
        DefaultTableModel model = (DefaultTableModel) tblRequestWorkqueue.getModel();

        model.setRowCount(0);

        for (WorkRequest request : companyMemberOrganization.getWorkQueue().getWorkRequestList()) {
           
           
            Object[] row = new Object[3];
            row[1] = ((IndividualWorkRequest) request).getSender();//requestor
            row[2] = ((IndividualWorkRequest) request).getReceiver() == null ? null : request.getReceiver().getPerson().getFirstName();//selector
            row[0] = ((IndividualWorkRequest) request);
//            row[3] = ((IndividualWorkRequest) request).getHelptype();

            model.addRow(row);
           // }
        
    }
   }
    
    
    
    private void completeDescriptionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeDescriptionBtnActionPerformed
        // TODO add your handling code here:    
     int selectedRow = tblRequestWorkqueue.getSelectedRow();

        if (selectedRow >= 0) {
            
        WorkRequest request = (WorkRequest) tblRequestWorkqueue.getValueAt(selectedRow, 0);  
        completeDescTextArea.setText("");
        completeDescTextArea.setText(((IndividualWorkRequest) request).getLngDescription());
        
        }
    }//GEN-LAST:event_completeDescriptionBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void btnRequestorProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestorProfileActionPerformed
      
        int selectedRow = tblRequestWorkqueue.getSelectedRow();

        if (selectedRow >= 0) {
            
        WorkRequest request = (WorkRequest) tblRequestWorkqueue.getValueAt(selectedRow, 0);
        workrequest = request;
 
        CompanyMemberRequestorCompleteProfileJPanel companyMemberRequestorCompleteProfileJPanel = new CompanyMemberRequestorCompleteProfileJPanel(userProcessContainer,account,workrequest);
        userProcessContainer.add("CompanyMemberRequestorCompleteProfileJPanel", companyMemberRequestorCompleteProfileJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnRequestorProfileActionPerformed

    private void earnSmileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_earnSmileBtnActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tblRequestWorkqueue.getSelectedRow();

        if (selectedRow >= 0) {
            WorkRequest request = (WorkRequest) tblRequestWorkqueue.getValueAt(selectedRow, 0);
            if ( (request.isComplete()) ||(request.isParticipate())) {
              JOptionPane.showMessageDialog(null, "Request already processed.");
                return;
            } 
            
            else {
               // request.setComplete(true);
                request.setParticipate(true);
                request.setReceiver(account);
                request.setStatus("Help is on the way");
                populateTable(companyMemberOrganization);

            }
        }
        
        
    }//GEN-LAST:event_earnSmileBtnActionPerformed

    private void tblRequestWorkqueueMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRequestWorkqueueMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblRequestWorkqueueMousePressed

    private void tblRequestWorkqueueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRequestWorkqueueMouseClicked
        // TODO add your handling code here:
        /*int selectedRow = tblRequestWorkqueue.getSelectedRow();
        WorkRequest request = (WorkRequest) tblRequestWorkqueue.getValueAt(selectedRow, 0);
        workrequest = request;
        lblrequestType.setText(workrequest.getType());
        lblrequestCountry.setText( ((IndividualWorkRequest) workrequest).getCountry());
        lblrequestState.setText( ((IndividualWorkRequest) workrequest).getState() );
        lblrequestCity.setText( ((IndividualWorkRequest) workrequest).getCity() );
         
        completeDescTextArea.setText(((IndividualWorkRequest) workrequest).getShrtDescription());
           
 //   (IndividualWorkRequest)workrequest).   */          
    }//GEN-LAST:event_tblRequestWorkqueueMouseClicked

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton btnRequestorProfile;
    private javax.swing.JTextArea completeDescTextArea;
    private javax.swing.JButton completeDescriptionBtn;
    private javax.swing.JButton earnSmileBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblRequestWorkqueue;
    // End of variables declaration//GEN-END:variables
}
