/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUInterface;

import Business.AirLiner;
import Business.Airplane;
import Business.Flight;
import Business.FlightFleet;
import Business.Seat;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author AbhilashKosaraju
 */
public class AddFlightsJPanel extends javax.swing.JPanel {

    private JPanel UserContainer;
    private FlightFleet Flightfleet;
    private Flight f;
    private Airplane air;
    private Seat seat;
    public String Name;
    public String Manu;
    public String License;

    AddFlightsJPanel(JPanel UserContainer, FlightFleet Flightfleet, String Name, String Manu, String License) {
        initComponents();
        this.UserContainer = UserContainer;
        this.Flightfleet = Flightfleet;
        this.Name = Name;
        this.Manu = Manu;
        this.License = License;

        System.out.println(Name + "Add Flights module");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        modelTextField = new javax.swing.JTextField();
        startPointTextField = new javax.swing.JTextField();
        destinationTextField = new javax.swing.JTextField();
        serialNumberTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        totalSeatsTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        availableTextField = new javax.swing.JTextField();
        addFlightBtn = new javax.swing.JButton();
        addAnotherBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        costTextField = new javax.swing.JTextField();

        jLabel1.setText("                Add Flights");

        jLabel2.setText("Model ");

        jLabel3.setText("StartPoint");

        jLabel4.setText("Destination");

        jLabel5.setText("SerialNumber");

        serialNumberTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                serialNumberTextFieldKeyPressed(evt);
            }
        });

        jLabel6.setText("TotalSeats");

        totalSeatsTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                totalSeatsTextFieldKeyPressed(evt);
            }
        });

        jLabel7.setText("AvailableSeats");

        availableTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                availableTextFieldKeyPressed(evt);
            }
        });

        addFlightBtn.setText("Add");
        addFlightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFlightBtnActionPerformed(evt);
            }
        });

        addAnotherBtn.setText("Add Another");
        addAnotherBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAnotherBtnActionPerformed(evt);
            }
        });

        backBtn.setText("<<Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jButton1.setText("Add New Flight");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setText("cost");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(modelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(costTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(startPointTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(destinationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(serialNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(availableTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(addFlightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(addAnotherBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBtn)
                        .addGap(193, 193, 193)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addComponent(jButton1)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(backBtn)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(modelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)
                                .addComponent(costTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addComponent(startPointTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(destinationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(serialNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(totalSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(availableTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addFlightBtn)
                    .addComponent(addAnotherBtn))
                .addGap(38, 38, 38)
                .addComponent(jButton1)
                .addContainerGap(405, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addFlightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFlightBtnActionPerformed

        for (AirLiner a : Flightfleet.getFlightfleet()) {
            if (a.getName().equals(Name)) {
                System.out.println("IN loop " + a.getName());
                a.getF().setStartpoint(startPointTextField.getText());
                a.getF().setDestination(destinationTextField.getText());
                a.getF().setAvailableseats(Integer.parseInt(availableTextField.getText()));
                a.getAp().setModel(modelTextField.getText());
                a.getF().setSerialNumber(Integer.parseInt(serialNumberTextField.getText()));
                a.getAp().setTotalseats(Integer.parseInt(totalSeatsTextField.getText()));
                JOptionPane.showMessageDialog(null, "Flight Added");
                break;
            }
        }

        startPointTextField.setText("");
        destinationTextField.setText("");
        availableTextField.setText("");
        modelTextField.setText("");
        serialNumberTextField.setText("");
        totalSeatsTextField.setText("");

    }//GEN-LAST:event_addFlightBtnActionPerformed

    private void addAnotherBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAnotherBtnActionPerformed
        // TODO add your handling code here:

        AirLiner a = Flightfleet.addAirliner();
        Flight f = new Flight();
        Airplane ap = new Airplane();
        Seat seat = new Seat();
        a.setLicense(License);
        a.setAvailablity(Manu);
        a.setName(Name);
        System.out.println(Name + Name);
        f.setStartpoint(startPointTextField.getText());
        f.setDestination(destinationTextField.getText());
        f.setAvailableseats(Integer.parseInt(availableTextField.getText()));
        ap.setModel(modelTextField.getText());
        f.setSerialNumber(Integer.parseInt(serialNumberTextField.getText()));
        ap.setTotalseats(Integer.parseInt(totalSeatsTextField.getText()));
        seat.setCost(Integer.parseInt(costTextField.getText()));
        a.setF(f);
        a.setAp(ap);
        a.getF().setSe(seat);

    }//GEN-LAST:event_addAnotherBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        UserContainer.remove(this);
        CardLayout layout = (CardLayout) UserContainer.getLayout();
        layout.previous(UserContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void serialNumberTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serialNumberTextFieldKeyPressed

        int key = evt.getKeyCode();
        if ((key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9) || (key >= evt.VK_0 && key <= evt.VK_9) || (key == evt.VK_BACK_SPACE)) {
            serialNumberTextField.setEditable(true);
        } else {
            serialNumberTextField.setEditable(false);
            JOptionPane.showMessageDialog(null, " Input format must be numbers");
            serialNumberTextField.setText("");
    }//GEN-LAST:event_serialNumberTextFieldKeyPressed

    }
    private void totalSeatsTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalSeatsTextFieldKeyPressed

        int key = evt.getKeyCode();
        if ((key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9) || (key >= evt.VK_0 && key <= evt.VK_9) || (key == evt.VK_BACK_SPACE)) {
            totalSeatsTextField.setEditable(true);
        } else {
            totalSeatsTextField.setEditable(false);
            JOptionPane.showMessageDialog(null, " Input format must be numbers");
            totalSeatsTextField.setText("");
        }


    }//GEN-LAST:event_totalSeatsTextFieldKeyPressed

    private void availableTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_availableTextFieldKeyPressed

        int key = evt.getKeyCode();
        if ((key >= evt.VK_NUMPAD0 && key <= evt.VK_NUMPAD9) || (key >= evt.VK_0 && key <= evt.VK_9) || (key == evt.VK_BACK_SPACE)) {
            availableTextField.setEditable(true);
        } else {
            availableTextField.setEditable(false);
            JOptionPane.showMessageDialog(null, " Input format must be numbers");
            availableTextField.setText("");
        }

    }//GEN-LAST:event_availableTextFieldKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AirLiner aips = new AirLiner();
        Flight f = new Flight();
        Airplane ap = new Airplane();
        Seat seat = new Seat();

        aips.setName(Name);
        aips.setAvailablity(Manu);
        aips.setLicense(License);
        f.setStartpoint(startPointTextField.getText());
        f.setDestination(destinationTextField.getText());
        f.setAvailableseats(Integer.parseInt(availableTextField.getText()));
        ap.setModel(modelTextField.getText());
        f.setSerialNumber(Integer.parseInt(serialNumberTextField.getText()));
        ap.setTotalseats(Integer.parseInt(totalSeatsTextField.getText()));
        seat.setCost(Integer.parseInt(costTextField.getText()));
        aips.setF(f);
        aips.setAp(ap);
        aips.getF().setSe(seat);

        JOptionPane.showMessageDialog(null, "Flight Added");


    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAnotherBtn;
    private javax.swing.JButton addFlightBtn;
    private javax.swing.JTextField availableTextField;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField costTextField;
    private javax.swing.JTextField destinationTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField modelTextField;
    private javax.swing.JTextField serialNumberTextField;
    private javax.swing.JTextField startPointTextField;
    private javax.swing.JTextField totalSeatsTextField;
    // End of variables declaration//GEN-END:variables
}
