/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUInterface;

import Business.AirLiner;
import Business.CustomerDirectory;
import Business.FlightFleet;
import Business.Seat;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author AbhilashKosaraju
 */
public class CutomerDealsJPanel extends javax.swing.JPanel {

    private JPanel UserContainer;
    private FlightFleet Flightfleet;
    private CustomerDirectory Directory;
    private Seat s;

    CutomerDealsJPanel(JPanel UserContainer, FlightFleet Flightfleet, CustomerDirectory Directory) {
        initComponents();
        this.Flightfleet = Flightfleet;
        this.Directory = Directory;
        this.UserContainer = UserContainer;
        populateFlightTable();

    }

    private void populateFlightTable() {
        DefaultTableModel fltb = (DefaultTableModel) displayFlightTable.getModel();
        fltb.setRowCount(0);

        for (AirLiner a : Flightfleet.getFlightfleet()) {

            Object row[] = new Object[15];

            row[0] = a;
            row[1] = a.getAvailablity();
            row[2] = a.getLicense();
            row[3] = a.getAp().getModel(); //a.getManufacturedYear();
            row[4] = a.getAp().getManYear();
            row[5] = a.getAp().getTotalseats();
            row[6] = a.getF().getSerialNumber();
            row[7] = a.getF().getStartpoint();
            row[8] = a.getF().getDeparttime();
            row[9] = a.getF().getDestination();
            row[10] = a.getF().getArrivetime();
            row[11] = a.getF().getAvailableseats();
            row[12] = a.getF().getReservedseats();
            row[13] = a.getF().getSe().getCost();

            fltb.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        startpointTextField = new javax.swing.JTextField();
        destinationTextField = new javax.swing.JTextField();
        getplanesBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        dealsTable = new javax.swing.JTable();
        bookaSeatBtn = new javax.swing.JButton();
        quicksearchTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayFlightTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("   Search Flight Database");

        jLabel2.setText("Startpoint");

        jLabel3.setText("Destination");

        startpointTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                startpointTextFieldKeyReleased(evt);
            }
        });

        destinationTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                destinationTextFieldKeyReleased(evt);
            }
        });

        getplanesBtn.setText("GetPlanes");
        getplanesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getplanesBtnActionPerformed(evt);
            }
        });

        dealsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airliner", "Availability", "License", "Model ", "Manufactured Year", "Total Seats", "Serial Number ", "Start Point ", "Depart Time ", "Destination", "Arrive Time ", "Available Seats ", "Reserved Seats", "Seat Cost"
            }
        ));
        jScrollPane2.setViewportView(dealsTable);

        bookaSeatBtn.setText("Book a Seat");
        bookaSeatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookaSeatBtnActionPerformed(evt);
            }
        });

        quicksearchTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                quicksearchTextFieldKeyReleased(evt);
            }
        });

        jLabel4.setText(" Quick Search :");

        backBtn.setText("<<Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        displayFlightTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airliner", "Availability", "License", "Model", "Manufactureed Year", "Total Seats", "Serial Number", "Start Point ", "Departure Time", "Destination", "Arrival Time", "Available Seats", "Total Seats", "Seat Cost"
            }
        ));
        jScrollPane1.setViewportView(displayFlightTable);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("                  Flight Database");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quicksearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(startpointTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(227, 227, 227)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(137, 137, 137)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(29, 29, 29)
                                .addComponent(destinationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(469, 469, 469)
                        .addComponent(getplanesBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(455, 455, 455)
                        .addComponent(bookaSeatBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(backBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1003, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1040, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startpointTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(destinationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quicksearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(getplanesBtn)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(bookaSeatBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(107, 107, 107))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void getplanesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getplanesBtnActionPerformed

        DefaultTableModel dltb = (DefaultTableModel) dealsTable.getModel();
        dltb.setRowCount(0);

        ArrayList<AirLiner> tempfleet;
        tempfleet = Flightfleet.searchAirplanes(startpointTextField.getText().toLowerCase(), destinationTextField.getText().toLowerCase());
        //Airliner a = new AirLiner();
        for (AirLiner a : tempfleet) {
            Object row[] = new Object[15];

            row[0] = a;
            row[1] = a.getAvailablity();
            row[2] = a.getLicense();
            row[3] = a.getAp().getModel(); //a.getManufacturedYear();
            row[4] = a.getAp().getManYear();
            row[5] = a.getAp().getTotalseats();
            row[6] = a.getF().getSerialNumber();
            row[7] = a.getF().getStartpoint();
            row[8] = a.getF().getDeparttime();
            row[9] = a.getF().getDestination();
            row[10] = a.getF().getArrivetime();
            row[11] = a.getF().getAvailableseats();
            row[12] = a.getF().getReservedseats();
            row[13] = a.getF().getSe().getCost();

            dltb.addRow(row);

        }


    }//GEN-LAST:event_getplanesBtnActionPerformed

    private void bookaSeatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookaSeatBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = dealsTable.getSelectedRow();
//         
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, " Select the concerned Row");
        } else {
            AirLiner arl = new AirLiner();
            arl = (AirLiner) dealsTable.getValueAt(selectedRow, 0);

            SeatReservationJPanel panel = new SeatReservationJPanel(UserContainer, Flightfleet, Directory, arl);
            UserContainer.add("AddAirlinerJPanel", panel);
            CardLayout layout = (CardLayout) UserContainer.getLayout();
            layout.next(UserContainer);
        }


    }//GEN-LAST:event_bookaSeatBtnActionPerformed

    private void quicksearchTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quicksearchTextFieldKeyReleased
        DefaultTableModel apft = (DefaultTableModel) displayFlightTable.getModel();
        String search = quicksearchTextField.getText();
        if (search.length() > 1) {
            search = search.substring(0, 1).toUpperCase() + search.substring(1, search.length());
        }
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(apft);

        displayFlightTable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_quicksearchTextFieldKeyReleased

    private void startpointTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_startpointTextFieldKeyReleased
        DefaultTableModel apft = (DefaultTableModel) displayFlightTable.getModel();
        String search = startpointTextField.getText();
        if (search.length() > 1) {
            search = search.substring(0, 1).toUpperCase() + search.substring(1, search.length());
        }
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(apft);

        displayFlightTable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_startpointTextFieldKeyReleased

    private void destinationTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_destinationTextFieldKeyReleased
        DefaultTableModel apft = (DefaultTableModel) displayFlightTable.getModel();
        String search = destinationTextField.getText();
        if (search.length() > 1) {
            search = search.substring(0, 1).toUpperCase() + search.substring(1, search.length());
        }
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(apft);

        displayFlightTable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_destinationTextFieldKeyReleased

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        UserContainer.remove(this);
        CardLayout layout = (CardLayout) UserContainer.getLayout();
        layout.previous(UserContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton bookaSeatBtn;
    private javax.swing.JTable dealsTable;
    private javax.swing.JTextField destinationTextField;
    private javax.swing.JTable displayFlightTable;
    private javax.swing.JButton getplanesBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField quicksearchTextField;
    private javax.swing.JTextField startpointTextField;
    // End of variables declaration//GEN-END:variables
}
