/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRole;

import Business.ConfigureBusiness;
import Business.User;
import javax.swing.JPanel;

/**
 *
 * @author sowjanya
 */
public class SalesWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel workAreaJPanel;
    private ConfigureBusiness business;
    private User user;
//    public SalesWorkAreaJPanel() {
//        
//        lblName.setText(user.getPerson().getName());
//        lblUsername.setText(user.getUserName());
//        lblRole.setText(user.getRole());
//    }

    SalesWorkAreaJPanel(JPanel workAreaJPanel, ConfigureBusiness business) {
        initComponents();
        this.business=business;
        this.workAreaJPanel=workAreaJPanel;
        this.user=user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 951, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
