/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminRole;

import Business.ConfigureBusiness;
import Business.Person;
import Business.User;
import UtilityServices.Utility;
import java.awt.CardLayout;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author AbhilashKosaraju
 */
public class AVUUserJPanel extends javax.swing.JPanel {

    private JPanel workAreaJPanel;
    private ConfigureBusiness business;
    private User user;

    public AVUUserJPanel(JPanel workAreaJPanel, ConfigureBusiness business, User user) {
        initComponents();
        this.workAreaJPanel = workAreaJPanel;
        this.business = business;
        this.user = user;
        this.rbtnActive.setActionCommand("true");
        this.rbtnDisabled.setActionCommand("false");
        rbtnActive.setSelected(true);
        int i = 0;
        Person[] perArr = new Person[business.getPersonDirectory().getPersonDirectory().size()];
        for (Person p : business.getPersonDirectory().getPersonDirectory()) {
            perArr[i] = p;
            i++;
        }
        comboPerson.setModel(new javax.swing.DefaultComboBoxModel(perArr));
        if (user != null) {
            txtDep.setText(user.getDepartment());
            txtUsername.setText(user.getUserName());
            txtPass.setText("********");
            comboPerson.setSelectedItem(user.getPerson());
            if (user.getRole().equals("HR Manager")) {
                comboRole.setSelectedIndex(0);
            } else if (user.getRole().equals("System Administrator")) {
                comboRole.setSelectedIndex(1);
            }
            if (user.isActive()) {
                rbtnActive.setSelected(true);
                rbtnDisabled.setSelected(false);
            } else {
                rbtnDisabled.setSelected(true);
                rbtnActive.setSelected(false);
            }
            btnAddNewUser.setText("Update");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        lblAUHead = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        comboPerson = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txtDep = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        comboRole = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        rbtnActive = new javax.swing.JRadioButton();
        rbtnDisabled = new javax.swing.JRadioButton();
        btnBack = new javax.swing.JButton();
        btnAddNewUser = new javax.swing.JButton();
        txtPass = new javax.swing.JPasswordField();

        jButton1.setText("jButton1");

        lblAUHead.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        lblAUHead.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAUHead.setText("Add User");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Person:");

        jLabel3.setText("Username:");

        jLabel4.setText("Password:");

        comboPerson.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Department:");

        jLabel6.setText("Role:");

        comboRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Customer", "Supplier", "Administrator", "Sales Rep" }));

        jLabel7.setText("Status:");

        rbtnActive.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbtnActive);
        rbtnActive.setText("Active");

        rbtnDisabled.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbtnDisabled);
        rbtnDisabled.setText("Disabled");

        btnBack.setBackground(new java.awt.Color(255, 51, 0));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAddNewUser.setBackground(new java.awt.Color(102, 102, 255));
        btnAddNewUser.setForeground(new java.awt.Color(255, 255, 255));
        btnAddNewUser.setText("Add");
        btnAddNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(comboRole, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtUsername)
                                            .addComponent(comboPerson, 0, 225, Short.MAX_VALUE)
                                            .addComponent(txtPass)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDep)))))
                        .addGap(94, 94, 94)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbtnActive)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnDisabled))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddNewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnActive)
                            .addComponent(rbtnDisabled))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDep, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboRole, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddNewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAUHead, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblAUHead, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 193, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        workAreaJPanel.remove(this);
        ManageUserWorkAreaJPanel backPanel = (ManageUserWorkAreaJPanel) workAreaJPanel.getComponent(workAreaJPanel.getComponents().length - 1);
        backPanel.populateUserTable();
        CardLayout layout = (CardLayout) workAreaJPanel.getLayout();
        layout.previous(workAreaJPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewUserActionPerformed
        String check = "";
        check = Utility.ValidateTextFields(txtUsername, true, 0, 0, 20);
        if (!check.equals("")) {
            JOptionPane.showMessageDialog(null, check, "Alert!", JOptionPane.WARNING_MESSAGE);
            return;
        }
        check = Utility.ValidateTextFields(txtDep, true, 0, 0, 20);
        if (!check.equals("")) {
            JOptionPane.showMessageDialog(null, check, "Alert!", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (txtPass.getPassword().length == 0 || txtPass.getPassword().length > 8) {
            JOptionPane.showMessageDialog(null, "Enter Password", "Alert!", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (user == null) {
            User nu = business.getUserDirectory().addUser();
            nu.setActive(Boolean.parseBoolean(buttonGroup1.getSelection().getActionCommand()));
            nu.setPerson((Person) comboPerson.getSelectedItem());
            nu.setRole(String.valueOf(comboRole.getSelectedItem()));
            nu.setDepartment(txtDep.getText());
            nu.setUserName(txtUsername.getText());
            nu.setPass(Utility.getHash(String.valueOf(txtPass.getPassword())));

            JOptionPane.showMessageDialog(null, "User created successfully", "Alert!", JOptionPane.INFORMATION_MESSAGE);
        } else {
            String dummy = "********";
            user.setDepartment(txtDep.getText());
            user.setUserName(txtUsername.getText());
            if (!Arrays.equals(txtPass.getPassword(), dummy.toCharArray())) {
                user.setPass(Utility.getHash(String.valueOf(txtPass.getPassword())));
            }
            user.setRole(String.valueOf(comboRole.getSelectedItem()));
            user.setPerson((Person) comboPerson.getSelectedItem());
            user.setActive(Boolean.parseBoolean(buttonGroup1.getSelection().getActionCommand()));

            JOptionPane.showMessageDialog(null, "User updated successfully", "Alert!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAddNewUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewUser;
    private javax.swing.JButton btnBack;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox comboPerson;
    private javax.swing.JComboBox<String> comboRole;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAUHead;
    private javax.swing.JRadioButton rbtnActive;
    private javax.swing.JRadioButton rbtnDisabled;
    private javax.swing.JTextField txtDep;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
